--liquibase formatted sql

--changeset mallim:1.0.1
CREATE TABLE app_user (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_expired bit(1) NOT NULL,
  account_locked bit(1) NOT NULL,
  address varchar(150) DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  country varchar(100) DEFAULT NULL,
  postal_code varchar(15) DEFAULT NULL,
  province varchar(100) DEFAULT NULL,
  credentials_expired bit(1) NOT NULL,
  email varchar(255) NOT NULL,
  account_enabled bit(1) DEFAULT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  password varchar(255) NOT NULL,
  password_hint varchar(255) DEFAULT NULL,
  phone_number varchar(255) DEFAULT NULL,
  username varchar(50) NOT NULL,
  version int DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  constraint email UNIQUE (email),
  constraint username UNIQUE (username)
);
--rollback drop table app_user;

--changeset mallim:1.0.2
CREATE TABLE role (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  description varchar(64) DEFAULT NULL,
  name varchar(20) DEFAULT NULL
);
--rollback drop table role;

--changeset mallim:1.0.3
CREATE TABLE user_role (
  user_id bigint NOT NULL,
  role_id bigint NOT NULL
);

CREATE INDEX idx_user_id
ON user_role(user_id);

CREATE INDEX idx_role_id
ON user_role(role_id);

ALTER TABLE role
ADD CONSTRAINT role_pk
PRIMARY KEY (id);

ALTER TABLE app_user
ADD CONSTRAINT app_user_pk
PRIMARY KEY (id);

ALTER TABLE user_role
ADD CONSTRAINT u_user_role
PRIMARY KEY (user_id,role_id);

ALTER TABLE user_role
ADD CONSTRAINT fk_role_id
FOREIGN KEY (role_id)
REFERENCES role(id);

ALTER TABLE user_role
ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id)
REFERENCES app_user(id);

--rollback drop table user_role;

--changeset mallim:testdata
insert into app_user(id,account_expired,account_locked,address,city,country,postal_code,province,credentials_expired,email,account_enabled,first_name,last_name,password,password_hint,phone_number,username,version,website)
values (-4,0,0,'','Denver','US','80210','CO',0,'user4@company.com',1,'user4','user4','$2a$10$CnQVJ9bsWBjMpeSKrrdDEeuIptZxXrwtI6CZ/OgtNxhIgpKxXeT9y','A male kitty.','','user4',1,'http://tomcat.apache.org');

insert into app_user(id,account_expired,account_locked,address,city,country,postal_code,province,credentials_expired,email,account_enabled,first_name,last_name,password,password_hint,phone_number,username,version,website)
values (-3,0,0,'','Denver','US','80210','CO',0,'two_roles_user@appfuse.org',1,'Two Roles','User','$2a$10$bH/ssqW8OhkTlIso9/yakubYODUOmh.6m5HEJvcBq3t3VdBh7ebqO','Not a female kitty.','','two_roles_user',1,'http://raibledesigns.com');

insert into app_user(id,account_expired,account_locked,address,city,country,postal_code,province,credentials_expired,email,account_enabled,first_name,last_name,password,password_hint,phone_number,username,version,website)
values (-2,0,0,'','Denver','US','80210','CO',0,'matt@raibledesigns.com',1,'Matt','Raible','$2a$10$bH/ssqW8OhkTlIso9/yakubYODUOmh.6m5HEJvcBq3t3VdBh7ebqO','Not a female kitty.','','admin',1,'http://raibledesigns.com');

insert into app_user(id,account_expired,account_locked,address,city,country,postal_code,province,credentials_expired,email,account_enabled,first_name,last_name,password,password_hint,phone_number,username,version,website)
values (-1,0,0,'','Denver','US','80210','CO',0,'matt_raible@yahoo.com',1,'Tomcat','User','$2a$10$CnQVJ9bsWBjMpeSKrrdDEeuIptZxXrwtI6CZ/OgtNxhIgpKxXeT9y','A male kitty.','','user',1,'http://tomcat.apache.org');

insert into role(id,description,name)
values (-2,'test descr','ROLE_USER');

insert into role(id,description,name)
values (-1,'Administrator role (can edit Users)','ROLE_ADMIN');

insert into user_role(user_id,role_id) values (-3,-2);
insert into user_role(user_id,role_id) values (-3,-1);
insert into user_role(user_id,role_id) values (-2,-1);
insert into user_role(user_id,role_id) values (-1,-2);

--rollback delete from app_user;
--rollback delete from role;
--rollback delete from user_role;




